<script lang="ts">
    import SvelteMarkdown from '$lib/index.js'
    import Unsupported from '$lib/test/issues/issue-214/Unsupported.svelte'
    import UnsupportedHTML from '$lib/test/issues/issue-214/UnsupportedHTML.svelte'

    const { source } = $props()
</script>

<SvelteMarkdown
    {source}
    renderers={{
        blockquote: Unsupported,
        del: Unsupported,
        image: Unsupported,
        heading: Unsupported,
        hr: Unsupported,
        table: Unsupported,
        tablehead: Unsupported,
        tablebody: Unsupported,
        tablerow: Unsupported,
        tablecell: Unsupported,
        html: {
            a: UnsupportedHTML,
            abbr: UnsupportedHTML,
            address: UnsupportedHTML,
            article: UnsupportedHTML,
            aside: UnsupportedHTML,
            audio: UnsupportedHTML,
            b: UnsupportedHTML,
            bdi: UnsupportedHTML,
            bdo: UnsupportedHTML,
            blockquote: UnsupportedHTML,
            br: UnsupportedHTML,
            button: UnsupportedHTML,
            canvas: UnsupportedHTML,
            cite: UnsupportedHTML,
            code: UnsupportedHTML,
            datalist: UnsupportedHTML,
            dd: UnsupportedHTML,
            del: UnsupportedHTML,
            details: UnsupportedHTML,
            dfn: UnsupportedHTML,
            dialog: UnsupportedHTML,
            div: UnsupportedHTML,
            dl: UnsupportedHTML,
            dt: UnsupportedHTML,
            em: UnsupportedHTML,
            embed: UnsupportedHTML,
            fieldset: UnsupportedHTML,
            footer: UnsupportedHTML,
            form: UnsupportedHTML,
            h1: UnsupportedHTML,
            h2: UnsupportedHTML,
            h3: UnsupportedHTML,
            h4: UnsupportedHTML,
            h5: UnsupportedHTML,
            h6: UnsupportedHTML,
            header: UnsupportedHTML,
            hgroup: UnsupportedHTML,
            hr: UnsupportedHTML,
            i: UnsupportedHTML,
            iframe: UnsupportedHTML,
            img: UnsupportedHTML,
            input: UnsupportedHTML,
            kbd: UnsupportedHTML,
            label: UnsupportedHTML,
            legend: UnsupportedHTML,
            li: UnsupportedHTML,
            main: UnsupportedHTML,
            mark: UnsupportedHTML,
            menu: UnsupportedHTML,
            meter: UnsupportedHTML,
            nav: UnsupportedHTML,
            ol: UnsupportedHTML,
            optgroup: UnsupportedHTML,
            option: UnsupportedHTML,
            output: UnsupportedHTML,
            p: UnsupportedHTML,
            param: UnsupportedHTML,
            picture: UnsupportedHTML,
            pre: UnsupportedHTML,
            progress: UnsupportedHTML,
            s: UnsupportedHTML,
            samp: UnsupportedHTML,
            section: UnsupportedHTML,
            select: UnsupportedHTML,
            small: UnsupportedHTML,
            source: UnsupportedHTML,
            span: UnsupportedHTML,
            strong: UnsupportedHTML,
            sub: UnsupportedHTML,
            summary: UnsupportedHTML,
            sup: UnsupportedHTML,
            table: UnsupportedHTML,
            tbody: UnsupportedHTML,
            td: UnsupportedHTML,
            textarea: UnsupportedHTML,
            tfoot: UnsupportedHTML,
            th: UnsupportedHTML,
            thead: UnsupportedHTML,
            tr: UnsupportedHTML,
            track: UnsupportedHTML,
            u: UnsupportedHTML,
            ul: UnsupportedHTML,
            var: UnsupportedHTML
        }
    }}
/>
