packages:
    - .
    - docs

allowBuilds:
    '@humanspeak/docs-kit': true
    '@humanspeak/docs-kit@https://codeload.github.com/humanspeak/docs-kit/tar.gz/0ec41c524be319a1a50a1edcf770dc327e79f04b': true
    '@humanspeak/docs-kit@https://codeload.github.com/humanspeak/docs-kit/tar.gz/30c325691f170eb5877519a4aac2f32015d02a5e': true
    esbuild: true
    sharp: true
    workerd: true

onlyBuiltDependencies:
    - '@humanspeak/docs-kit'
    - esbuild
    - sharp
    - workerd

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
    - '@humanspeak/*'
