packages:
    - .
    - docs

allowBuilds:
    '@humanspeak/docs-kit@https://codeload.github.com/humanspeak/docs-kit/tar.gz/3e332eb43d0dddd8a9033307755f35da5e886e41': true
    '@humanspeak/docs-kit': true
    esbuild: true
    sharp: true
    workerd: true

onlyBuiltDependencies:
    - '@humanspeak/docs-kit'
    - esbuild
    - sharp
    - workerd

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
    - '@humanspeak/*'
