<script lang="ts">
    import { CodeReferenceV2, ExampleV2 } from '@humanspeak/docs-kit'
    import { getSeoContext } from '$lib/components/contexts/Seo/Seo.context'
    import MarkdownPlayground from '$lib/examples/playground/demos/MarkdownPlayground.svelte'
    import { Edit3, Eye, Zap } from '@lucide/svelte'
    // Generated by docs-kit's `demoManifestPlugin` (vite.config.ts) — single
    // source of truth: editing the .svelte file regenerates this entry and
    // the displayed code stays in lockstep with the rendered demo.
    import demoManifest from '$lib/demo-manifest.json'
    import type { Snippet } from 'svelte'

    const seo = getSeoContext()
    if (seo) {
        seo.title = 'Live Playground | Examples | Svelte Markdown'
        seo.description =
            'Interactive markdown playground with live preview. Edit markdown and HTML in real-time, powered by @humanspeak/svelte-markdown.'
        seo.ogTitle = 'Live Playground'
        seo.ogTagline = 'Edit markdown and HTML with real-time preview.'
        seo.ogFeatures = ['Edit & Preview', 'Real-Time', 'Markdown + HTML', 'Full Editor']
        seo.ogSlug = 'examples-playground'
    }

    const SOURCE_URL =
        'https://github.com/humanspeak/svelte-markdown/blob/main/docs/src/lib/examples/'

    type Section = {
        figId: string
        tag: string
        title: { prefix?: string; accent: string; end?: string }
        description: string
        snippet: Snippet
        codeSnippet?: Snippet
        notes?: Snippet
        mode?: 'live' | 'static'
        barCells?: { k: string; v: string }[]
        sourceUrl?: string
    }

    type ManifestEntry = {
        code: string
        lang: string
        html?: { light: string; dark: string }
    }
    const manifest = demoManifest as Record<string, ManifestEntry>

    const sections: Section[] = [
        {
            figId: 'FIG-001',
            tag: 'DEMO',
            title: { prefix: 'live ', accent: 'playground', end: '.' },
            description:
                'Edit markdown on the left, see it rendered on the right. Mix markdown with HTML — both render in real time with a 500ms debounce.',
            snippet: playgroundSection,
            codeSnippet: playgroundCode,
            notes: playgroundNotes,
            barCells: [{ k: 'demo', v: 'markdown + preview' }],
            sourceUrl: `${SOURCE_URL}playground/demos/MarkdownPlayground.svelte`
        }
    ]

    const pad2 = (n: number) => String(n).padStart(2, '0')
</script>

{#snippet playgroundSection()}
    <MarkdownPlayground />
{/snippet}
{#snippet playgroundNotes()}
    <ul>
        <li>
            <Edit3 />
            <span>
                Type or paste markdown on the left. Inline HTML — <code>&lt;em&gt;</code>,
                <code>&lt;span style&gt;</code>, <code>&lt;a&gt;</code> — renders right alongside.
            </span>
        </li>
        <li>
            <Eye />
            <span>
                The preview updates 500ms after the last keystroke, so large pastes don't thrash the
                renderer.
            </span>
        </li>
        <li>
            <Zap />
            <span>
                Powered by the same <code>SvelteMarkdown</code> you'd drop into your own app — no special
                playground harness.
            </span>
        </li>
    </ul>
{/snippet}

{#snippet playgroundCode()}
    <CodeReferenceV2
        samples={[
            {
                id: 'markdown-playground',
                label: 'MarkdownPlayground.svelte',
                ...manifest['playground/demos/MarkdownPlayground.svelte']
            }
        ]}
        columns={1}
    />
{/snippet}

{#each sections as section, i (section.figId)}
    <ExampleV2
        figId={section.figId}
        tag={section.tag}
        title={section.title}
        description={section.description}
        mode={section.mode ?? 'live'}
        sheetLabel="SHEET {pad2(i + 1)} / {pad2(sections.length)}"
        barCells={section.barCells}
        sourceUrl={section.sourceUrl}
        codeSnippet={section.codeSnippet}
        codeLabel="show code"
        notes={section.notes}
    >
        {@render section.snippet()}
    </ExampleV2>
{/each}
