import { SiGithub, SiHtml5, SiJavascript, SiNpm } from '@icons-pack/svelte-simple-icons'
import {
    ArrowRight,
    ArrowRightLeft,
    BookOpen,
    Box,
    Check,
    ChevronDown,
    ChevronRight,
    Code,
    Copy,
    Download,
    ExternalLink,
    Eye,
    Feather,
    FileText,
    Filter,
    FlaskConical,
    Gauge,
    Grid2x2,
    Heading,
    Heart,
    Lightbulb,
    Link,
    List,
    LoaderCircle,
    Lock,
    Moon,
    Paintbrush,
    Pen,
    Play,
    Puzzle,
    Recycle,
    Rocket,
    RotateCw,
    Scissors,
    Settings,
    Shield,
    ShieldCheck,
    ShieldHalf,
    SquarePen,
    Sun,
    Superscript,
    TextCursor,
    Trash2,
    TriangleAlert,
    WandSparkles,
    Workflow,
    Zap
} from '@lucide/svelte'

export const iconMap = {
    'arrow-right': ArrowRight,
    'arrow-right-left': ArrowRightLeft,
    'book-open': BookOpen,
    box: Box,
    check: Check,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    code: Code,
    copy: Copy,
    download: Download,
    'external-link': ExternalLink,
    eye: Eye,
    feather: Feather,
    'file-text': FileText,
    filter: Filter,
    'flask-conical': FlaskConical,
    gauge: Gauge,
    'grid-2x2': Grid2x2,
    heading: Heading,
    heart: Heart,
    lightbulb: Lightbulb,
    link: Link,
    list: List,
    'loader-circle': LoaderCircle,
    lock: Lock,
    moon: Moon,
    paintbrush: Paintbrush,
    pen: Pen,
    play: Play,
    puzzle: Puzzle,
    recycle: Recycle,
    rocket: Rocket,
    'rotate-cw': RotateCw,
    scissors: Scissors,
    settings: Settings,
    shield: Shield,
    'shield-check': ShieldCheck,
    'shield-half': ShieldHalf,
    'square-pen': SquarePen,
    sun: Sun,
    superscript: Superscript,
    'text-cursor': TextCursor,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    'wand-sparkles': WandSparkles,
    workflow: Workflow,
    zap: Zap,
    // Brand icons
    github: SiGithub,
    npm: SiNpm,
    html5: SiHtml5,
    javascript: SiJavascript
} as const

export type IconName = keyof typeof iconMap
