name: Cloudflare Pages - Deploy

permissions:
    contents: read

on:
    pull_request:
        types: [closed]
        paths:
            - docs/**
            - .github/workflows/cloudflare-pages.yml
        branches:
            - main
    workflow_dispatch:
        # trunk-ignore(checkov/CKV_GHA_7)
        inputs: {}

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
              with:
                  persist-credentials: false

            - uses: pnpm/action-setup@v4 # zizmor: ignore[unpinned-uses]
              with:
                  version: 10

            - name: Use Node.js - 22
              uses: actions/setup-node@v4 # zizmor: ignore[unpinned-uses]
              with:
                  node-version: 22

            - name: Install Root Dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build Package
              run: pnpm run build

            - name: Deploy Docs
              working-directory: docs
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                  pnpm install --no-frozen-lockfile
                  pnpm run deploy
